#peter keres
#3-1-2020

# simple make file that complies and loads the example 1 program for kotlin

all:
	@clear
	@echo '*********** LOADING KOTLIN EXAMPLE 1 **************'
	@javac *.java
	@clear
	@java Tester